apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}server-config
type: Opaque
stringData:
  server.yml: |-
    db:
      host: {{ default (printf "%s-postgresql.%s" .Release.Name .Release.Namespace) .Values.db.host }}
      port: {{ .Values.db.port }}
      dbname: {{ .Values.db.dbname }}
      user: {{ .Values.db.user }}
      password: {{ .Values.db.password }}
    log:
      format: {{ .Values.log.format }}
    server:
      addr: {{ .Values.server.addr }}
      cookie:
        secure: {{ .Values.server.cookie.secure }}
      basic_auth:
        enabled: {{ .Values.server.basicAuth.enabled }}
        username: {{ .Values.server.basicAuth.username }}
        password: {{ .Values.server.basicAuth.password }}
      oauth2:
        github:
          auth_url: {{ .Values.server.oauth2.github.authUrl }}
          client_id: {{ .Values.server.oauth2.github.clientId | quote }}
          client_secret: {{ .Values.server.oauth2.github.clientSecret | quote }}
          redirect_uri: {{ .Values.server.oauth2.github.redirectUri }}
          scopes: {{ .Values.server.oauth2.github.scopes }}
          token_url: {{ .Values.server.oauth2.github.tokenUrl }}
