{{- if .Capabilities.APIVersions.Has "batch/v1/CronJob" }}
apiVersion: batch/v1
{{- else }}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}syncer
spec:
  schedule: "0 10 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
        {{- with .Values.syncer.cronjob.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          restartPolicy: Never
          initContainers:
            - {{- include "chart.checkDbIsReadyInitContainer" . | nindent 14 }}
          containers:
            - name: syncer
              image: {{ .Values.syncer.cronjob.image.repository }}:{{ .Values.imageTag | default (printf "v%s" .Chart.AppVersion) }}
              imagePullPolicy: {{ .Values.pullPolicy }}
              {{- with .Values.syncer.cronjob.containerSecurityContext }}
              securityContext:
                {{- toYaml . | nindent 16 }}
              {{- end }}
              resources:
                {{- toYaml .Values.syncer.cronjob.resources | nindent 16 }}
              volumeMounts:
                - name: syncer-config
                  mountPath: {{ .Values.configDir | quote }}
                  readOnly: true
              command: ['gitjobs-syncer', '-c', '{{ .Values.configDir }}/syncer.yml']
          volumes:
            - name: syncer-config
              secret:
                secretName: {{ include "chart.resourceNamePrefix" . }}syncer-config
