name: Build images

on:
  push:
    branches:
      - main

env:
  OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
  OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
  OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
  OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
  OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}

jobs:
  build-dbmigrator-image:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Login to OCI Registry
        id: login-ocir
        uses: oracle-actions/login-ocir@v1.3.0
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
      - name: Get gitjobs-dbmigrator OCIR repository
        id: get-ocir-repository-dbmigrator
        uses: oracle-actions/get-ocir-repository@v1.3.0
        with:
          name: gitjobs/dbmigrator
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}
      - name: Build and push gitjobs-dbmigrator image
        env:
          OCIR_REPOSITORY: ${{ steps.get-ocir-repository-dbmigrator.outputs.repo_path }}
        run: |
          docker build \
            -f database/migrations/Dockerfile \
            -t $OCIR_REPOSITORY:$GITHUB_SHA \
            .
          docker push $OCIR_REPOSITORY:$GITHUB_SHA

  build-server-image:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Login to OCI Registry
        id: login-ocir
        uses: oracle-actions/login-ocir@v1.3.0
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
      - name: Get gitjobs-server OCIR repository
        id: get-ocir-repository-server
        uses: oracle-actions/get-ocir-repository@v1.3.0
        with:
          name: gitjobs/server
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}
      - name: Build and push gitjobs-server image
        env:
          OCIR_REPOSITORY: ${{ steps.get-ocir-repository-server.outputs.repo_path }}
        run: |
          docker build \
            -f gitjobs-server/Dockerfile \
            -t $OCIR_REPOSITORY:$GITHUB_SHA \
            .
          docker push $OCIR_REPOSITORY:$GITHUB_SHA

  build-syncer-image:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Login to OCI Registry
        id: login-ocir
        uses: oracle-actions/login-ocir@v1.3.0
        with:
          auth_token: ${{ secrets.OCI_AUTH_TOKEN }}
      - name: Get gitjobs-syncer OCIR repository
        id: get-ocir-repository-syncer
        uses: oracle-actions/get-ocir-repository@v1.3.0
        with:
          name: gitjobs/syncer
          compartment: ${{ secrets.OCI_COMPARTMENT_OCID }}
      - name: Build and push gitjobs-syncer image
        env:
          OCIR_REPOSITORY: ${{ steps.get-ocir-repository-syncer.outputs.repo_path }}
        run: |
          docker build \
            -f gitjobs-syncer/Dockerfile \
            -t $OCIR_REPOSITORY:$GITHUB_SHA \
            .
          docker push $OCIR_REPOSITORY:$GITHUB_SHA
