name: End-to-end tests
on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
      - name: Install Playwright
        run: npm i -D @playwright/test
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --config tests/e2e/playwright.config.ts
